name: travel_clothing
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/   # optional, include full assets folder

  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif_28pt-Regular.ttf
        - asset: assets/fonts/RobotoSerif_28pt-Bold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
